import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ExamProtectionWrapper from "./components/ExamProtectionWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CBT Gis Unesa",
  description: "Generated by GIS Unesa",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ExamProtectionWrapper>
          {children}
        </ExamProtectionWrapper>
      </body>
    </html>
  );
}
